name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Tensor Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: pip install numpy tqdm requests torch pytest
    - name: Run Pytest 
      run: python -m pytest -s -v